# load detector
/lcdd/url target.gdml

/random/setSeeds 12345 67890

/hps/generators/verbose 2

# generate beam particles for one bunch
/hps/generators/create BeamGen BEAM
#/hps/generators/BeamGen/param nelectrons 1
/hps/generators/BeamGen/verbose 2

# event selection for beam particles
/hps/plugins/load BeamTrackSelectionPlugin
/hps/plugins/BeamTrackSelectionPlugin/verbose 2

# init the run
/run/initialize

# LCIO output
/hps/lcio/verbose 2
/hps/lcio/recreate
/hps/lcio/file beam_selection_test.slcio

/run/beamOn 1000
