/lcdd/url detector.lcdd

# merge in event stream
/hps/lcio/merge/add MergeTest1
/hps/lcio/merge/MergeTest1/file tritrig1.slcio

/run/initialize

/hps/lcio/verbose 4
/hps/lcio/file lcio_merge_test.slcio
/hps/lcio/recreate

# enable detailed event info
/hps/lcio/dumpEventDetailed

# enable event summary
/hps/lcio/dumpEventSummary

/run/beamOn 100

# test dump of file
/hps/lcio/dumpFile lcio_merge_test.slcio 10 42
