#
# Event overlay macro similar to tritrig-wab-beam generation
#

# load detector
/lcdd/url detector.lcdd

# print info as event generation runs
/hps/generators/verbose 2

# overlay trident signal using poisson distribution dervied from cross section
/hps/generators/create TriGen LHE
/hps/generators/TriGen/file tritrig_unweighted_events.lhe
/hps/generators/TriGen/sample sigma 0.0
/hps/generators/TriGen/verbose 2

# overlay WAB events using poisson distribution derived from cross section
/hps/generators/create WabGen LHE
/hps/generators/WabGen/file wab_unweighted_events.lhe
/hps/generators/WabGen/sample sigma 0.0
/hps/generators/WabGen/verbose 2

# generate beam backgrounds
/hps/generators/create BeamGen BEAM
#/hps/generators/BeamGen/param nelectrons 1
/hps/generators/BeamGen/verbose 2

# plugin for selecting tracks from beam-target interaction
/hps/plugins/load BeamTrackSelectionPlugin
/hps/plugins/BeamTrackSelectionPlugin/verbose 2

# init the run
/run/initialize

# LCIO output
/hps/lcio/verbose 2
/hps/lcio/recreate
/hps/lcio/file sigma_test.slcio

# number of events
/run/beamOn 1000
