/lcdd/url detector.lcdd

# merge in event stream
/hps/lcio/merge/add MergeTest1
/hps/lcio/merge/MergeTest1/file tritrig1.slcio
/hps/lcio/merge/MergeTest1/filter/eventModulus 2

# merge in the same event stream for testing
/hps/lcio/merge/add MergeTest2
/hps/lcio/merge/MergeTest2/file tritrig1.slcio
/hps/lcio/merge/MergeTest2/filter/ecalEnergy 50 MeV

/run/initialize

/hps/lcio/verbose 4
/hps/lcio/file lcio_merge_test.slcio
/hps/lcio/recreate

/run/beamOn 100
