# load detector
/lcdd/url detector.lcdd

/hps/generators/verbose 2

# define LHE event generator with multiple files
/hps/generators/create MyTest LHE
/hps/generators/MyTest/file wab_5mrad_unweighted_events_000001.lhe 
/hps/generators/MyTest/file wab_5mrad_unweighted_events_000002.lhe 
/hps/generators/MyTest/file wab_5mrad_unweighted_events_000003.lhe
/hps/generators/MyTest/verbose 2

# init the run
/run/initialize

# LCIO output
/hps/lcio/verbose 2
/hps/lcio/recreate
/hps/lcio/file lhe_multi_test.slcio

/run/beamOn 99999
