# load detector
/lcdd/url detector.lcdd

# read from WAB or other signal file
/hps/generators/create SigGen LHE
/hps/generators/SigGen/file signal1.lhe

# read from beam backgrounds file
/hps/generators/create BackgroundGen1 STDHEP
/hps/generators/BackgroundGen1/file beam1.stdhep

# read from beam backgrounds file
/hps/generators/create BackgroundGen2 STDHEP
/hps/generators/BackgroundGen2/file beam2.stdhep

# init the run
/run/initialize

# LCIO output
#/hps/lcio/verbose 4
/hps/lcio/file overlay_test.slcio

# plugin defs
#/hps/plugins/load DummySimPlugin

/run/beamOn 10
