# load detector
/lcdd/url detector.lcdd

# read a signal event and apply event transforms
/hps/generators/create SigGen LHE
/hps/generators/SigGen/file signal1.lhe
#/hps/generators/SigGen/transform/pos 0. 0. -5
/hps/generators/SigGen/transform/randz 0.004
/hps/generators/SigGen/transform/smear 0.300 0.030 0.0
/hps/generators/SigGen/transform/rot 0.0305

# init the run
/run/initialize

# LCIO output
/hps/lcio/verbose 2
/hps/lcio/file sample_test.slcio

# plugin defs
#/hps/plugins/load DummySimPlugin

/run/beamOn 10
