# load detector
/lcdd/url detector.lcdd

# print info as event generation runs
/hps/generators/verbose 2

# overlay WAB events using cross section from LHE file
/hps/generators/create WabGen LHE
/hps/generators/WabGen/file wab_unweighted_events.lhe
/hps/generators/WabGen/sample sigma 0
/hps/generators/WabGen/transform/rot 0.0305
/hps/generators/WabGen/verbose 2

# overlay trident events using using cross section from LHE file
/hps/generators/create TriGen LHE
/hps/generators/TriGen/file tritrig_unweighted_events.lhe
/hps/generators/TriGen/sample sigma 0
/hps/generators/TriGen/transform/rot 0.0305
/hps/generators/TriGen/verbose 2

# randomly sample beam backgrounds from StdHep file
/hps/generators/create BeamGen STDHEP
/hps/generators/BeamGen/file beam1.stdhep
/hps/generators/BeamGen/random
/hps/generators/BeamGen/sample poisson 1.7
/hps/generators/BeamGen/transform/rot 0.0305
/hps/generators/BeamGen/verbose 2

# init the run
/run/initialize

# LCIO output
/hps/lcio/verbose 2
/hps/lcio/recreate
/hps/lcio/file wab-beam-tri_test.slcio

# number of events
/run/beamOn 500000
